{{- if .Values.enableGoogleApplicationCredentials }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-bigquery-tech-adapter-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: witboost-secret-store
    kind: ClusterSecretStore
  target:
    name: google-bigquery-tech-adapter-secrets
  dataFrom:
    - extract:
        key: "google-bigquery-tech-adapter"
        decodingStrategy: Auto
  {{- end }}