apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: witboost-secret-store
spec:
  provider:
    fake:
      data:
        - key: "google-bigquery-tech-adapter"
          valueMap:
            GOOGLE_APPLICATION_CREDENTIALS: "" # base64 encoded file content
